// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/search": {
            "get": {
                "description": "Search flights with filters and sorting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Flights"
                ],
                "summary": "Search flights",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Origin airport code (e.g. CGK)",
                        "name": "origin",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination airport code (e.g. DPS)",
                        "name": "destination",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Departure date (YYYY-MM-DD)",
                        "name": "departure_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of passengers",
                        "name": "passengers",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cabin class (economy, business)",
                        "name": "cabin_class",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum price (IDR)",
                        "name": "min_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum price (IDR)",
                        "name": "max_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum stops",
                        "name": "max_stops",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum duration (minutes)",
                        "name": "max_duration",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Airline codes (CSV or repeated), e.g. GA,ID",
                        "name": "airlines",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Earliest departure time (HH:MM)",
                        "name": "earliest_departure",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Latest departure time (HH:MM)",
                        "name": "latest_departure",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Earliest arrival time (HH:MM)",
                        "name": "earliest_arrival",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Latest arrival time (HH:MM)",
                        "name": "latest_arrival",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "price_asc",
                            "price_desc",
                            "duration_asc",
                            "duration_desc",
                            "departure_asc",
                            "arrival_asc",
                            "best_value"
                        ],
                        "type": "string",
                        "description": "Sort option",
                        "name": "sort_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Flight"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Flight": {
            "type": "object",
            "properties": {
                "aircraft": {
                    "type": "string"
                },
                "airline": {
                    "type": "string"
                },
                "airlineCode": {
                    "type": "string"
                },
                "amenities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "arrivalTime": {
                    "type": "string"
                },
                "availableSeats": {
                    "type": "integer"
                },
                "baggage": {
                    "type": "string"
                },
                "departureTime": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "durationMin": {
                    "type": "integer"
                },
                "flightCode": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "priceIDR": {
                    "type": "integer",
                    "format": "int64"
                },
                "stops": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BOOKCABIN Flight Search API",
	Description:      "Flight search aggregation service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
